global:
  enabled: true
%{ if tls == "disabled" ~}
  tlsDisable: true
%{ else }
  tlsDisable: false
%{ endif ~}
injector:
  # True if you want to enable vault agent injection.
  enabled: true
server:
  image:
    repository: "${vault_repo}"
    tag: "${vault_version}"
    pullPolicy: IfNotPresent
  updateStrategyType: "OnDelete"
  logLevel: "${log_level}"
  
  enterpriseLicense:
    # The name of the Kubernetes secret that holds the enterprise license. The
    # secret must be in the same namespace that Vault is installed into.
    secretName: "${license_secret}"
    # The key within the Kubernetes secret that holds the enterprise license.
    secretKey: "license"

  # readinessProbe:
  #   # ready if unsealed, either active or standby or performancestandby
  #   enabled: true
  #   path: /v1/sys/health?standbycode=204&performancestandbycode=204&drsecondarycode=204

  # livenessProbe:
  #   # alive if vault is successfully responding to requests
  #   enabled: true
  #   path: /v1/sys/health?standbyok=true&perfstandbyok=true&sealedcode=204&uninitcode=204&drsecondarycode=204
  #   initialDelaySeconds: 30

  postStart: []
  # - /bin/sh
  # - -c
  # - /vault/userconfig/myscript/run.sh

  extraEnvironmentVars:
    GOOGLE_REGION: "${gcp_region}"
    GOOGLE_PROJECT: "${gcp_project}"
    GOOGLE_APPLICATION_CREDENTIALS: "/vault/userconfig/${kms_creds}/credentials.json"
    VAULT_CACERT: /vault/userconfig/vault-server-tls/vault_ca.crt
    # We need to increase the timeout to not get a context cancelled when working with Google KMS and private GKE clusters
    VAULT_CLIENT_TIMEOUT: "300s"

  # extraVolumes is a list of extra volumes to mount. These will be exposed
  # to Vault in the path `/vault/userconfig/<name>/`. The value below is
  # an array of objects, examples are shown below.
  extraVolumes:
    - type: 'secret'
      name: '${kms_creds}'
    - type: 'secret'
      name: 'vault-server-tls'
    #   path: null # default is `/vault/userconfig`

  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ template "vault.name" . }}
              app.kubernetes.io/instance: "{{ .Release.Name }}"
              component: server
          topologyKey: kubernetes.io/hostname

  # Enables a headless service to be used by the Vault Statefulset
  service:
    enabled: true
    # clusterIP: None
    # type: "NodePort"
    # nodePort: 30000
    # port: 8200
    # targetPort: 8200
    # annotations: {}

  # dataStorage:
  #   enabled: true
  #   # Size of the PVC created
  #   size: 10Gi
  #   storageClass: null
  #   accessMode: ReadWriteOnce

  # auditStorage:
  #   enabled: false
  #   # Size of the PVC created
  #   size: 10Gi
  #   storageClass: null
  #   accessMode: ReadWriteOnce

  ha:
    enabled: true
    replicas: ${vault_nodes}

    # If set to null, this will be set to the Pod IP Address
    apiAddr: null

    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true
        listener "tcp" {
%{ if tls == "disabled" ~}
          tls_disable = 1
%{ endif ~}
          address = "[::]:8200"
          cluster_address = "[::]:8201"
%{ if tls == "enabled" ~}
          tls_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
          tls_key_file = "/vault/userconfig/vault-server-tls/vault.key"
          tls_client_ca_file = "/vault/userconfig/vault-server-tls/vault_ca.crt"
%{ endif ~}
        }
        storage "raft" {
          path = "/vault/data"
%{ for leader_host in hosts ~}
          retry_join {
            leader_api_addr = "${http}://${leader_host}.vault-internal:8200"
%{ if tls == "enabled" ~}
            leader_ca_cert_file = "/vault/userconfig/vault-server-tls/vault_ca.crt"
            leader_client_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
            leader_client_key_file = "/vault/userconfig/vault-server-tls/vault.key"
%{ endif ~}
          }
%{ endfor ~}
        }
        service_registration "kubernetes" {}
        # Using GCP KMP
        seal "gcpckms" {
          project     = "${gcp_project}"
          region      = "${gcp_region}"
          key_ring    = "${key_ring}"
          crypto_key  = "${crypto_key}"
        }
        replication {
          resolver_discover_servers = false
        }
        reporting {
          license {
              enabled = false
          }
        }


# Vault UI
ui:
  enabled: true
  serviceType: "LoadBalancer"
  # serviceNodePort: null
  externalPort: 8200
csi:
  enabled: true
